<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="1" total="2" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-07-26T22:11:27 IST" name="Default suite" finished-at="2022-07-26T22:11:50 IST" duration-ms="22545">
    <groups>
    </groups>
    <test started-at="2022-07-26T22:11:27 IST" name="Default test" finished-at="2022-07-26T22:11:50 IST" duration-ms="22545">
      <class name="TestClasses.VerifyUserCanAddNewAddress">
        <test-method is-config="true" signature="beforeClass()[pri:0, instance:TestClasses.VerifyUserCanAddNewAddress@7b2bbc3]" started-at="2022-07-26T22:11:27 IST" name="beforeClass" finished-at="2022-07-26T22:11:47 IST" duration-ms="19509" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:TestClasses.VerifyUserCanAddNewAddress@7b2bbc3]" started-at="2022-07-26T22:11:47 IST" name="beforeMethod" finished-at="2022-07-26T22:11:47 IST" duration-ms="86" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="verifyUserCanAddNewAddress()[pri:1, instance:TestClasses.VerifyUserCanAddNewAddress@7b2bbc3]" started-at="2022-07-26T22:11:47 IST" name="verifyUserCanAddNewAddress" finished-at="2022-07-26T22:11:49 IST" duration-ms="2010" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "POMClasses.ProfilePage.clickOnManageAddress()" because "this.pp" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "POMClasses.ProfilePage.clickOnManageAddress()" because "this.pp" is null
at TestClasses.VerifyUserCanAddNewAddress.verifyUserCanAddNewAddress(VerifyUserCanAddNewAddress.java:72)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUserCanAddNewAddress -->
        <test-method is-config="true" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:TestClasses.VerifyUserCanAddNewAddress@7b2bbc3]" started-at="2022-07-26T22:11:49 IST" name="afterMethod" finished-at="2022-07-26T22:11:49 IST" duration-ms="274" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyUserCanAddNewAddress status=FAILURE method=VerifyUserCanAddNewAddress.verifyUserCanAddNewAddress()[pri:1, instance:TestClasses.VerifyUserCanAddNewAddress@7b2bbc3] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="afterClass()[pri:0, instance:TestClasses.VerifyUserCanAddNewAddress@7b2bbc3]" started-at="2022-07-26T22:11:49 IST" name="afterClass" finished-at="2022-07-26T22:11:50 IST" duration-ms="551" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- TestClasses.VerifyUserCanAddNewAddress -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
